name: Create Issue

on:
  workflow_run:
    workflows: [".NET Core Build and Publish"]
    types:
      - completed

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Issue
        uses: octokit/request-action@v1
        with:
          route: POST /repos/:owner/:repo/issues
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          title: "Issue triggered automatically by ${{ github.actor }}"
          body: "This issue was created automatically by a GitHub Actions workflow."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
